### ISSUE TITLE
AttributeError: module 'librosa' has no attribute 'output'

### ISSUE THREAD

**Issue by ropinheiro** [nestyme/Subtitles-generator#4]
When I run this command:

`python3 recognize.py -video Flow.mp4`

It apparently works until this part, where an error occurs:

```
(...)
video duration, hours: 0.6886200050390526
Traceback (most recent call last):
  File "recognize.py", line 55, in <module>
    split_into_frames('current.wav')
  File "recognize.py", line 49, in split_into_frames
    librosa.output.write_wav('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)
AttributeError: module 'librosa' has no attribute 'output'
```
A `current.wav` is generated, but no subtitles file appears.

**Comment by Mladia** [comment]
librosa does not support output anymore
from librosa changelogs:
#917 The output module is now deprecated, and will be removed in version 0.8.

**Comment by Sadam1195** [comment]
you can substitute 

`librosa.output.write_wav('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)`

 with

```
import soundfile as sf
sf.write('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)
```
in your code.

@ropinheiro

**Comment by sangramsingnk** [comment]
(Speech) Sangram:resample sing$ python resample.py 
Traceback (most recent call last):
  File "resample.py", line 8, in <module>
    librosa.output.write_wav(newFilename, y_16, 16000)
AttributeError: module 'librosa' has no attribute 'output'

**Comment by Sadam1195** [comment]
> (Speech) Sangram:resample sing$ python resample.py
> Traceback (most recent call last):
> File "resample.py", line 8, in
> librosa.output.write_wav(newFilename, y_16, 16000)
> AttributeError: module 'librosa' has no attribute 'output'

Please edit the code in `resample.py `with the comments in https://github.com/nestyme/Subtitles-generator/issues/4#issuecomment-811855424
@Sangramsingkayte

**Comment by carlosmatthews** [comment]
Hy , I edit the code in resample.py with the comments in #4 (comment).

sf.write('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)`

but I get an error with the new library (soundfile)

File "C:\Python38\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'samples/A.wav': System error.

@Sadam1195

**Comment by Sadam1195** [comment]
> Hy , I edit the code in resample.py with the comments in #4 (comment).
> 
> sf.write('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)`
> 
> but I get an error with the new library (soundfile)
> 
> File "C:\Python38\lib\site-packages\soundfile.py", line 1357, in _error_check
> raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
> RuntimeError: Error opening 'samples/A.wav': System error.


Error indicates that you do not have `samples` folder in that directory. Please create `samples` folder manually and rerun the code. 

@carlosmatthews

**Comment by carlosmatthews** [comment]
thanks, @Sadam1195 , Thank you very much I did not find the problem
