### ISSUE TITLE
TypeError: No format specified and unable to get format from file extension: 'samples/\\.wav'

### ISSUE THREAD

**Issue by carlosmatthews** [nestyme/Subtitles-generator#7]
When I try to run the program, it recognizes a file older than 1 hour, this error occurs, it seems to have to do with how it names the files into which it segments the original audio. To name the files it uses letters (A-Z) and when the letters are finished it begins to use symbols like: "/". I'm not sure but I think this may be the problem and you should try changing it by using names to name the segments

Traceback (most recent call last):
  File "recognize.py", line 60, in <module>
    split_into_frames('current.wav')
  File "recognize.py", line 55, in split_into_frames
    sf.write('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr) # new library soundfile as sf remplace librosa.ouput # modificacion carlos
  File "C:\Python38\lib\site-packages\soundfile.py", line 314, in write
    with SoundFile(file, 'w', samplerate, channels,
  File "C:\Python38\lib\site-packages\soundfile.py", line 627, in __init__
    self._info = _create_info_struct(file, mode, samplerate, channels,
  File "C:\Python38\lib\site-packages\soundfile.py", line 1416, in _create_info_struct
    format = _get_format_from_filename(file, mode)
  File "C:\Python38\lib\site-packages\soundfile.py", line 1457, in _get_format_from_filename
    raise TypeError("No format specified and unable to get format from "
TypeError: No format specified and unable to get format from file extension: 'samples/\\.wav'

**Comment by asctime** [comment]
same under win32, i thought it was broken dir-sep escaping.

**Comment by asctime** [comment]
It's just a folder glob, so you can make life much easier just changing the end of 'split_into_frames' (in recognize.py) to something like this:

```
        # original code:
        #librosa.output.write_wav('samples/{}.wav'.format(chr(int(i/50)+65)), tmp_batch, sr)
        sf.write('samples/{}.wav'.format(int(i/50)), tmp_batch, sr)
```
